In [2]:
import torch

### Tensors in Pytorch 
1. What are **tensors** -> These are specialized multi-dimensional array for mathematical operations.
2. **Dimension** -> 1D Tensor spans in 1 direction, 2D spans in 2 directions....nD dimension n directions
3. **Examples of Tensors**
<br> 3.1 --> 0D tensor = Scalar Value 
<br> 3.2 --> 1D tensor = One dimensional vector
<br> 3.3 --> 2D tensor = Matrices --> Grayscale images
<br> 3.4 --> 3D tensor = Coloured Images 
<br> 3.5 --> 4D tensor = Batches of images (32,10,10,3) 

In [3]:
# empty tensor 
a = torch.empty(2,3) # no values are assigned
a

tensor([[-3.0757e-05,  1.8861e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
# type check 
type(a)

torch.Tensor

In [5]:
# zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# ones 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(3,3) # Random values between 0 and 1

tensor([[0.4368, 0.9270, 0.8888],
        [0.3408, 0.2114, 0.0343],
        [0.2639, 0.2048, 0.7167]])

In [8]:
# Seed and Manual Seed --> Random Tensors will give different values each time
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [9]:
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [10]:
torch.tensor([[1,2,3],[4,5,6]]) # List to tensor convert

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# Linearly space 
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [12]:
# Identity matrix 
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Tensor Shapes

In [13]:
a.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(a) # Similar shape another tensor to create

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
a.dtype

torch.float32

### Reduction Operations

In [17]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.sum(a)

tensor(9.)

In [19]:
torch.sum(a,dim=1)

tensor([3., 3., 3.])

In [20]:
torch.sum(a,dim=0)

tensor([3., 3., 3.])

In [21]:
torch.argmax(a)

tensor(0)

In [22]:
torch.argmin(a)

tensor(0)

In [23]:
torch.relu_(a) # _ underscore represents inplace assignment of the values

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Copying of Tensors

In [25]:
a1 = torch.zeros(3,3)
a1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
b1 = a1
b1[0][0] = 1

In [ ]:
b1,a1 # Change in b impacts a as well

(tensor([[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
c1 = a1.clone()
c1[0][1] = 1
c1,a1 # Different now

(tensor([[1., 1., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
id(a1), id(b1) ,id(c1) # Different memory address for C1

(2252010536016, 2252010536016, 2251352121072)

### GPU operations of the tensor

In [33]:
import torch
import time 

In [34]:
torch.cuda.is_available()

False

In [35]:
device = torch.device('cuda')

In [36]:
device

device(type='cuda')

In [ ]:
torch.rand((2,3),device=device) # Need to compile pytorch using cuda

AssertionError: Torch not compiled with CUDA enabled

### Reshaping of Tensors

In [38]:
a1 = torch.ones(4,4)
a1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
a1.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [41]:
a1.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# Adding New Dimension 
image = torch.rand(226,226,3)
image.shape

torch.Size([226, 226, 3])

In [ ]:
image.unsqueeze(0).shape # Adding a dimension at 0th position   

torch.Size([1, 226, 226, 3])

In [44]:
# Numpy to Pytorch moving 
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [47]:
torch.from_numpy(a)

tensor([1, 2, 3])

In [49]:
a1.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

### Pytorch AutoGrad Functionality
1. Automatic Differentiation Tool

In [77]:
import torch 

x = torch.tensor(3.0,requires_grad=True) # In order to take derivative we will set require grad as true

In [62]:
y = x**2

In [63]:
x,y

(tensor(3., requires_grad=True), tensor(9., grad_fn=<PowBackward0>))

In [64]:
# dy / dx 
y.backward() # Backward differentiation is done, now you can go back to x

In [65]:
x.grad

tensor(6.)

In [78]:
# Another Example 

y = x**2
z = torch.sin(y)

In [79]:
y,z

(tensor(9., grad_fn=<PowBackward0>), tensor(0.4121, grad_fn=<SinBackward0>))

In [80]:
z.backward()

In [81]:
x.grad # This is the backward derivative

tensor(-5.4668)