In [2]:
import torch

### Tensors in Pytorch 
1. What are **tensors** -> These are specialized multi-dimensional array for mathematical operations.
2. **Dimension** -> 1D Tensor spans in 1 direction, 2D spans in 2 directions....nD dimension n directions
3. **Examples of Tensors**
<br> 3.1 --> 0D tensor = Scalar Value 
<br> 3.2 --> 1D tensor = One dimensional vector
<br> 3.3 --> 2D tensor = Matrices --> Grayscale images
<br> 3.4 --> 3D tensor = Coloured Images 
<br> 3.5 --> 4D tensor = Batches of images (32,10,10,3) 

In [3]:
# empty tensor 
a = torch.empty(2,3) # no values are assigned
a

tensor([[-3.0757e-05,  1.8861e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
# type check 
type(a)

torch.Tensor

In [5]:
# zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# ones 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(3,3) # Random values between 0 and 1

tensor([[0.4368, 0.9270, 0.8888],
        [0.3408, 0.2114, 0.0343],
        [0.2639, 0.2048, 0.7167]])

In [8]:
# Seed and Manual Seed --> Random Tensors will give different values each time
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [9]:
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [10]:
torch.tensor([[1,2,3],[4,5,6]]) # List to tensor convert

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# Linearly space 
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [12]:
# Identity matrix 
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Tensor Shapes

In [13]:
a.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(a) # Similar shape another tensor to create

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
a.dtype

torch.float32

### Reduction Operations

In [17]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.sum(a)

tensor(9.)

In [19]:
torch.sum(a,dim=1)

tensor([3., 3., 3.])

In [20]:
torch.sum(a,dim=0)

tensor([3., 3., 3.])

In [21]:
torch.argmax(a)

tensor(0)

In [22]:
torch.argmin(a)

tensor(0)

In [23]:
torch.relu_(a) # _ underscore represents inplace assignment of the values

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Copying of Tensors

In [25]:
a1 = torch.zeros(3,3)
a1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
b1 = a1
b1[0][0] = 1

In [ ]:
b1,a1 # Change in b impacts a as well

(tensor([[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
c1 = a1.clone()
c1[0][1] = 1
c1,a1 # Different now

(tensor([[1., 1., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
id(a1), id(b1) ,id(c1) # Different memory address for C1

(2252010536016, 2252010536016, 2251352121072)

### GPU operations of the tensor

In [33]:
import torch
import time 

In [34]:
torch.cuda.is_available()

False

In [35]:
device = torch.device('cuda')

In [36]:
device

device(type='cuda')

In [ ]:
torch.rand((2,3),device=device) # Need to compile pytorch using cuda

AssertionError: Torch not compiled with CUDA enabled

### Reshaping of Tensors

In [38]:
a1 = torch.ones(4,4)
a1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
a1.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [41]:
a1.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# Adding New Dimension 
image = torch.rand(226,226,3)
image.shape

torch.Size([226, 226, 3])

In [ ]:
image.unsqueeze(0).shape # Adding a dimension at 0th position   

torch.Size([1, 226, 226, 3])

In [44]:
# Numpy to Pytorch moving 
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [47]:
torch.from_numpy(a)

tensor([1, 2, 3])

In [49]:
a1.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

### Pytorch AutoGrad Functionality
1. Automatic Differentiation Tool

In [77]:
import torch 

x = torch.tensor(3.0,requires_grad=True) # In order to take derivative we will set require grad as true

In [62]:
y = x**2

In [63]:
x,y

(tensor(3., requires_grad=True), tensor(9., grad_fn=<PowBackward0>))

In [64]:
# dy / dx 
y.backward() # Backward differentiation is done, now you can go back to x

In [65]:
x.grad

tensor(6.)

In [78]:
# Another Example 

y = x**2
z = torch.sin(y)

In [79]:
y,z

(tensor(9., grad_fn=<PowBackward0>), tensor(0.4121, grad_fn=<SinBackward0>))

In [80]:
z.backward()

In [81]:
x.grad # This is the backward derivative

tensor(-5.4668)

In [11]:
# Lets run an example on Sigmoid + Binary Cross Entropy 
import torch

def bce(pred,target):
    epsilon = 1e-8 
    pred = torch.clamp(pred,epsilon,1-epsilon)
    return -(target*torch.log(pred)+(1-target)*(torch.log(1-pred)))

x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

In [12]:
w,b

(tensor(1., requires_grad=True), tensor(0., requires_grad=True))

In [13]:
z = w*x+b
y_pred = torch.sigmoid(z)

In [14]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [15]:
loss = bce(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [16]:
loss.backward()

In [17]:
print(w.grad,b.grad)

tensor(6.6918) tensor(0.9988)


### Simple Neural Network using Pytorch

In [2]:
import torch
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [16]:
# Train Test Split
X_train, X_test,y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [17]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [18]:
pd.DataFrame(y_train)

diagnosis
356         B
292         B
405         B
229         M
459         B
..        ...
413         B
180         M
150         B
220         B
352         M

[455 rows x 1 columns]

In [19]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [21]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [23]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [24]:
X_train_tensor.shape

torch.Size([455, 30])

In [25]:
X_train_tensor

tensor([[-0.3085, -0.1618, -0.2873,  ...,  0.1504,  0.3243, -0.0501],
        [-0.3363, -0.7778, -0.3660,  ..., -0.1537,  0.7512,  0.6555],
        [-0.8966, -0.1618, -0.8805,  ..., -0.5561, -1.0540, -0.3758],
        ...,
        [-0.3224,  0.3631, -0.3511,  ..., -0.7956,  0.4570, -1.0981],
        [-0.1412, -1.4632, -0.1748,  ..., -0.5307, -0.8477,  0.1732],
        [ 3.2261, -0.4326,  3.3086,  ...,  2.4055,  1.2468,  0.2273]],
       dtype=torch.float64)

In [72]:
# Lets Define the Simple Model 


class NeuralNetwork:
    def __init__(self,X,learning_rate,epochs):
        self.learning_rate =  learning_rate
        self.epochs = epochs
        self.weights = torch.rand(X.shape[1],1,
                                  dtype=torch.float64,
                                  requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,
                                  requires_grad=True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        loss = -((y*torch.log(y_pred)) + (1-y)*torch.log(1-y_pred)).mean()
        return loss
    
learning_rate = 0.1
epochs = 25

In [73]:
model = NeuralNetwork(X_train_tensor,learning_rate,epochs=epochs)

In [74]:
#model.weights,model.bias

In [93]:
# Training Loop 
epochs = 50
for epoch in range(epochs):
    # Forward Pass 
    y_pred = model.forward(X_train_tensor)
    # Loss Calculate 
    loss = model.loss_function(y_pred,y_train_tensor)
    print(f" Epoch {epoch+1} : {loss}")
    # Backward Pass 
    loss.backward()
    # Change weight
    with torch.no_grad():
        # Use -= for in-place subtraction 
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero Gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

 Epoch 1 : 0.8709058977429968
 Epoch 2 : 0.8523449533203444
 Epoch 3 : 0.8376254563594064
 Epoch 4 : 0.8255777627743409
 Epoch 5 : 0.8153926181162913
 Epoch 6 : 0.8065293662494359
 Epoch 7 : 0.7986343837122338
 Epoch 8 : 0.7914782962021117
 Epoch 9 : 0.7849115833060497
 Epoch 10 : 0.7788349135491202
 Epoch 11 : 0.7731801002867025
 Epoch 12 : 0.7678982235691918
 Epoch 13 : 0.7629523709170418
 Epoch 14 : 0.7583132587229876
 Epoch 15 : 0.7539566071012247
 Epoch 16 : 0.7498615633195133
 Epoch 17 : 0.7460097447497954
 Epoch 18 : 0.7423846454533111
 Epoch 19 : 0.7389712561498127
 Epoch 20 : 0.7357558103229002
 Epoch 21 : 0.7327256061243955
 Epoch 22 : 0.7298688750598172
 Epoch 23 : 0.7271746806185346
 Epoch 24 : 0.7246328369255977
 Epoch 25 : 0.7222338414105218
 Epoch 26 : 0.7199688177230191
 Epoch 27 : 0.7178294664217144
 Epoch 28 : 0.7158080217360507
 Epoch 29 : 0.7138972131840376
 Epoch 30 : 0.7120902311448908
 Epoch 31 : 0.71038069570411
 Epoch 32 : 0.7087626282462173
 Epoch 33 : 0.70723

In [94]:
loss

tensor(0.6903, dtype=torch.float64, grad_fn=<NegBackward0>)

In [95]:
# Model Evaluation 
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.95).float()
    accuracy = (y_pred==y_test_tensor).float().mean()
    print("Accuracy  : ",accuracy)

Accuracy  :  tensor(0.6404)


### NN Module in Pytorch

1. Build neural network using NN 
2. Built in activation function 
3. Built in loss function 
4. Built in Optimizer 

In [110]:
import torch 
import torch.nn as nn 

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out 

In [111]:
features = torch.rand(10,5)
model = Model(5)

In [112]:
model(features) # Automatically calls the forward method inside the class

tensor([[0.4616],
        [0.5575],
        [0.5379],
        [0.4632],
        [0.5353],
        [0.4747],
        [0.4392],
        [0.4741],
        [0.4489],
        [0.5007]], grad_fn=<SigmoidBackward0>)

In [115]:
# show model weights
model.linear.weight,model.linear.bias

(Parameter containing:
 tensor([[ 0.2070, -0.2270, -0.3992, -0.2454,  0.0876]], requires_grad=True),
 Parameter containing:
 tensor([0.2220], requires_grad=True))

In [119]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Dataloader Class In Pytroch

### Building ANN

### Building CNN

### Building RNN