In [1]:
import numpy as np

**Matrix Vector Dot Product**

In [4]:
import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
    if len(a[0])!=len(b):
        return -1 
    c = np.dot(np.array(a),np.array(b))
    return c.tolist()

In [6]:
a = [[1, 2], [2, 4]]
b = [1, 2]
matrix_dot_vector(a,b)

[5, 10]

**Transpose of a Matrix**

In [9]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    b = np.array(a).T
    return b.tolist()

a = [[1,2,3],[4,5,6]]
transpose_matrix(a)

[[1, 4], [2, 5], [3, 6]]

**Find the Image of a Matrix Using Row Echelon Form**
 
Read Row Echelon Form to solve this 


In [10]:
import sympy as sp

def matrix_image(A):
    M = sp.Matrix(A)
    _, pivot_indices = M.rref()
    return M[:, pivot_indices]

In [11]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix_image(matrix))

Matrix([[1, 2], [4, 5], [7, 8]])


**Cosine Similarity Between Vectors**

In [12]:
def cosine_similarity(v1, v2):
    numerator  = np.dot(np.array(v1),np.array(v2))
    denominator = np.dot(np.linalg.norm(v1),np.linalg.norm(v2))
    similarity = numerator/denominator
    return np.round(similarity,3)


v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 6])
print(cosine_similarity(v1,v2))

1.0


**Othogonal Projection of a Vector onto a line**

In [ ]:
def orthogonal_projection(v,l):
    vl = np.dot(v,l)
    ll = np.dot(l,l)
    return (vl/ll)*np.array(l)

v = [3,4]
l = [1,0]
orthogonal_projection(v,l)

array([3., 0.])

**Inverse of a matrix**

In [25]:
from numpy.linalg import inv
arr = np.array([[1,2],[2,1]])
inv(arr)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

**Check if a matrix is invertible or not**
- Check Invertibility: Verify that M is invertible by ensuring determinants are non-zero.

In [29]:
m = np.array([[2,0],[0,2]])
if np.linalg.det(m)==0:
    print("Not Invertible")
else:
    print("Invertible")

Invertible


**Calculate 2x2 Matrix Inverse**

In [30]:
def inverse_2x2(matrix: list[list[float]]) -> list[list[float]]:
    matrix_det = matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
    inverse = [[matrix[1][1]/matrix_det,(-1*matrix[0][1])/matrix_det],
                [(-1*matrix[1][0])/matrix_det,matrix[0][0]/matrix_det]]
    return inverse

print(inverse_2x2([[4, 7], [2, 6]]))

[[0.6, -0.7], [-0.2, 0.4]]


**Eigen Values and Eigen Vectors**

In [33]:
def calculate_eigenvalues(matrix: list[list[float|int]]) -> list[float]:
    arr = np.array(matrix)
    eigenvalues,eigenvectors = np.linalg.eig(arr)
    return eigenvalues.tolist()

print(calculate_eigenvalues([[2, 1], [1, 2]]))

[3.0, 1.0]


### Jacobi Method to Solve Linear Equations

In [4]:
import numpy as np

# 1. Initialization
A = np.array([
    [5, -2, 3], 
    [-3, 9, 1], 
    [2, -1, -7]
], dtype=float)

b = np.array([-1, 2, 3], dtype=float)
n = 2

# Start with an initial guess of zeros for x
x = np.zeros_like(b)

# Extract the diagonal (aii) and the off-diagonal elements
D = np.diag(A)
R = A - np.diagflat(D)

print("Value of D : ",D)
print("Value of R : ",R)

# 2. Iteration
print(f"Initial x: {x}\n")

for i in range(n):
    # Vectorized computation of the formula: x[i] = (1/aii) * (b[i] - sum(aij * x[j]))
    x = np.round((b - np.dot(R, x)) / D,3)
    print(f"Iteration {i + 1}: {x}")

Value of D :  [ 5.  9. -7.]
Value of R :  [[ 0. -2.  3.]
 [-3.  0.  1.]
 [ 2. -1.  0.]]
Initial x: [0. 0. 0.]

Iteration 1: [-0.2    0.222 -0.429]
Iteration 2: [ 0.146  0.203 -0.517]


### Eigen Value and Eigen Vectors

In [13]:
data = np.array([[1, 2], [3, 4]])
eigen_values,eigen_vectors = np.linalg.eig(data)
print("Eigen Values : ",eigen_values)
print("Eigen Vectors : ",eigen_vectors)

Eigen Values :  [-0.37228132  5.37228132]
Eigen Vectors :  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# Covariance matrix
np.cov(data)

array([[0.5, 0.5],
       [0.5, 0.5]])

### PCA Implementation

1. Data Centered to zero
2. Covariance Matrix 
3. Find Eigen Value and Eigen Vectors
4. Pick the k PC

In [32]:
data = np.array([[1, 2], [3, 4], [5, 6]])
k = 1

# Center the data
data_mean = (data-data.mean(axis=0))
cov_matrix = np.cov(data_mean, rowvar=False)
evals,evectors = np.linalg.eigh(cov_matrix)
evals,evectors

(array([0., 8.]),
 array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [33]:
# eigh() returns them in ascending order, so we reverse the arrays
sorted_indices = np.argsort(evals)[::-1]
sorted_eigenvalues = evals[sorted_indices]

In [34]:
sorted_eigenvalues

array([8., 0.])

In [37]:
sorted_eigenvectors = evectors[:, sorted_indices]

In [38]:
sorted_eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [39]:
eigenvector_subset = sorted_eigenvectors[:, 0:k]

In [40]:
eigenvector_subset

array([[0.70710678],
       [0.70710678]])

In [41]:
X_reduced = np.dot(data_mean, eigenvector_subset)

In [42]:
X_reduced

array([[-2.82842712],
       [ 0.        ],
       [ 2.82842712]])